### ISSUE TITLE
Can't open a session remotely using Ubuntu

### ISSUE THREAD

**Issue by blasrodri** [Antti/rust-amqp#57]
Hi! 

When opening a session using `Session::open_url`  and `cargo run --no-default-features` I am getting the following error.

```
thread 'main' panicked at 'Can't create session: IoError(ConnectionRefused)', src/main.rs:53
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: order_scheduler::new_algorithm_instance_subscription
             at ./src/main.rs:53
   8: order_scheduler::main
             at ./src/main.rs:40
   9: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  10: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  11: main
  12: __libc_start_main
  13: _start

```

my Cargo.Toml

```
[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
amqp = "0.1.0"
postgres = { version = "0.14", features = ["with-chrono"] }
chrono = "0.3"
r2d2 = "0.7.2"
r2d2_postgres = "0.12.0"
```

My OS specs on Docker

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

My Docker version: 

```
Docker version 17.03.1-ce, build c6d412e
```

When I run this on my MAC Sierra, or on another Ubuntu then it connects using **the same credentials**. I am wondering if there is a library that is not required to compile, but it is using during the session creation?

**Comment by nicoCalvo** [comment]
Furthermore,
The same error is found in Ubuntu without docker and in Red Hat without docker as well.

The workaround I found was to tunneling port forwarding through SSH to localhost. This way there's no error and you can get connectivity and consume messages:

ssh -L 5672:localhost:5672 user@ip

Once the port-forwarding is up, you could simply change the rabbit address to point to 127.0.0.1 and the system will do the rest.

Please provide a solution since it can be replicated in many different platforms. Thank you.

**Comment by blasrodri** [comment]
FYI: I moved to https://github.com/sozu-proxy/lapin 
It seems that it has this issue solved.
